const terminal=document.querySelector('#terminal-output');
const terminalLines=[['> connecting to server...','dim'],['✓ QBCore detected','ok'],['✓ Database connected','ok'],['✓ 48 resources scanned','ok'],['',''],['! Found 17 errors','warn'],['> isolating resource conflicts...','dim'],['> patching dependencies...','dim'],['bar',''],['✓ Server optimized','ok']];
let lineIndex=0;function addTerminalLine(){if(lineIndex>=terminalLines.length)return;const [text,kind]=terminalLines[lineIndex++];if(text==='bar'){const bar=document.createElement('div');bar.className='bar';bar.innerHTML='<i></i>';terminal.append(bar)}else{const p=document.createElement('p');p.className=kind;p.textContent=text;terminal.append(p)}setTimeout(addTerminalLine,text===''?250:520)}setTimeout(addTerminalLine,650);
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const counters=document.querySelectorAll('[data-count]');const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=Number(el.dataset.count),start=performance.now(),duration=1300;function tick(now){const value=Math.min(target,Math.round(target*((now-start)/duration)));el.innerHTML=(el.dataset.prefix||'')+value+(el.dataset.suffix||'');if(value<target)requestAnimationFrame(tick)}requestAnimationFrame(tick);counterObserver.unobserve(el)}),{threshold:.6});counters.forEach(c=>counterObserver.observe(c));
document.querySelector('.menu').addEventListener('click',e=>{const nav=document.querySelector('.nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});document.querySelectorAll('.nav nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.nav').classList.remove('open')));
window.addEventListener('scroll',()=>document.querySelector('.scroll-progress').style.width=`${scrollY/(document.documentElement.scrollHeight-innerHeight)*100}%`,{passive:true});document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{if(innerWidth<761)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${-y*4}deg) rotateY(${x*4}deg) translateY(-4px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
const canvas=document.querySelector('#particles'),ctx=canvas.getContext('2d');let dots=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;dots=Array.from({length:Math.min(55,Math.floor(innerWidth/24))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.4+.3,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);dots.forEach(d=>{d.x+=d.vx;d.y+=d.vy;if(d.x<0||d.x>canvas.width)d.vx*=-1;if(d.y<0||d.y>canvas.height)d.vy*=-1;ctx.fillStyle='rgba(149,236,255,.34)';ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize);
